export enum EventTopic {
  //Communication Service
  ACCOUNT_ACTIVATION = 'ACCOUNT-ACTIVATION',
  LOGIN_OTP_GENERATED = 'LOGIN-OTP-GENERATED',
  RESET_PASSWORD = 'RESET-PASSWORD',

  LOG_ADDED = 'LOG-ADDED',
  EXCEPTION_LOG_ADDED = 'EXCEPTION-LOG-ADDED',
  API_REQUEST_COMPLETED = 'API-REQUEST-COMPLETED',
}
